from pathlib import Path
import sqlite3
import subprocess
import sys

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import FileResponse


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DB_FILE = PROJECT_ROOT / "db" / "roaming_lab.db"
RUN_PROJECT_FILE = PROJECT_ROOT / "run_project.py"
MARKDOWN_REPORT = PROJECT_ROOT / "reports" / "validation_test_report.md"


app = FastAPI(
    title="Roaming Billing CDR Validation API",
    description=(
        "API layer for a mock roaming billing integration lab. "
        "It exposes validation issues, billing results, reconciliation summaries, "
        "run history, and technical reports generated by the CLI pipeline."
    ),
    version="1.0.0",
)


ALLOWED_TABLES = {
    "validation_issues": "validation_issues",
    "billing_results": "billing_results",
    "billing_summary": "billing_summary",
    "reconciliation_summary": "reconciliation_summary",
    "cdr_records": "cdr_records",
}


def get_connection() -> sqlite3.Connection:
    if not DB_FILE.exists():
        raise HTTPException(
            status_code=404,
            detail=(
                "Database not found. Run the pipeline first: "
                "python run_project.py --input data/mock_roaming_cdrs.csv"
            ),
        )

    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    return conn


def fetch_rows(table_name: str, limit: int = 50) -> list[dict]:
    if table_name not in ALLOWED_TABLES:
        raise HTTPException(status_code=400, detail="Table is not allowed.")

    safe_table = ALLOWED_TABLES[table_name]

    with get_connection() as conn:
        try:
            rows = conn.execute(
                f"SELECT * FROM {safe_table} ORDER BY id DESC LIMIT ?",
                (limit,),
            ).fetchall()
        except sqlite3.OperationalError as exc:
            raise HTTPException(
                status_code=404,
                detail=f"Table not found or database not initialized: {exc}",
            ) from exc

    return [dict(row) for row in rows]


@app.get("/")
def root() -> dict:
    return {
        "message": "Roaming Billing CDR Validation API",
        "docs": "Open http://127.0.0.1:8000/docs",
    }


@app.get("/health")
def health() -> dict:
    return {
        "status": "ok",
        "database_exists": DB_FILE.exists(),
        "database_path": str(DB_FILE.relative_to(PROJECT_ROOT)),
        "report_exists": MARKDOWN_REPORT.exists(),
    }


@app.post("/pipeline/run")
def run_pipeline(
    input_path: str = Query(
        default="data/mock_roaming_cdrs.csv",
        description="Path to input CDR CSV file relative to project root.",
    )
) -> dict:
    if not RUN_PROJECT_FILE.exists():
        raise HTTPException(
            status_code=500,
            detail="run_project.py was not found.",
        )

    result = subprocess.run(
        [sys.executable, str(RUN_PROJECT_FILE), "--input", input_path],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        raise HTTPException(
            status_code=500,
            detail={
                "message": "Pipeline failed.",
                "stdout": result.stdout,
                "stderr": result.stderr,
            },
        )

    return {
        "status": "completed",
        "input_path": input_path,
        "stdout": result.stdout,
    }


@app.get("/runs")
def get_runs(limit: int = Query(default=10, ge=1, le=100)) -> list[dict]:
    with get_connection() as conn:
        try:
            rows = conn.execute(
                """
                SELECT *
                FROM run_history
                ORDER BY run_timestamp_utc DESC
                LIMIT ?
                """,
                (limit,),
            ).fetchall()
        except sqlite3.OperationalError as exc:
            raise HTTPException(
                status_code=404,
                detail=f"Run history table not found: {exc}",
            ) from exc

    return [dict(row) for row in rows]


@app.get("/table-counts")
def get_table_counts() -> list[dict]:
    with get_connection() as conn:
        try:
            rows = conn.execute(
                "SELECT * FROM latest_table_counts"
            ).fetchall()
        except sqlite3.OperationalError as exc:
            raise HTTPException(
                status_code=404,
                detail=f"Table counts view not found: {exc}",
            ) from exc

    return [dict(row) for row in rows]


@app.get("/validation-issues")
def get_validation_issues(
    limit: int = Query(default=50, ge=1, le=500)
) -> list[dict]:
    return fetch_rows("validation_issues", limit)


@app.get("/billing-results")
def get_billing_results(
    limit: int = Query(default=50, ge=1, le=500)
) -> list[dict]:
    return fetch_rows("billing_results", limit)


@app.get("/billing-summary")
def get_billing_summary(
    limit: int = Query(default=50, ge=1, le=500)
) -> list[dict]:
    return fetch_rows("billing_summary", limit)


@app.get("/reconciliation-summary")
def get_reconciliation_summary(
    limit: int = Query(default=50, ge=1, le=500)
) -> list[dict]:
    return fetch_rows("reconciliation_summary", limit)


@app.get("/cdr-records")
def get_cdr_records(
    limit: int = Query(default=50, ge=1, le=500)
) -> list[dict]:
    return fetch_rows("cdr_records", limit)


@app.get("/report/markdown")
def get_markdown_report() -> FileResponse:
    if not MARKDOWN_REPORT.exists():
        raise HTTPException(
            status_code=404,
            detail="Markdown report not found. Run the pipeline first.",
        )

    return FileResponse(
        path=MARKDOWN_REPORT,
        media_type="text/markdown",
        filename="validation_test_report.md",
    )